# Wilhelm Lange

## Week 11 - 31/3/2026
### Python Numpy Intro



In [1]:
What is Numpy? 
- NumPy is a python library
- NUmPy is short for "Numberical Python"
- 50x faster than python lists

SyntaxError: invalid syntax (<ipython-input-1-2b1e343c4a27>, line 1)

In [2]:
import numpy as np
import random

In [6]:
lst = random.choices(range(5,11), k=15)
lst

[6, 9, 6, 5, 8, 9, 9, 5, 9, 5, 7, 8, 5, 9, 8]

In [7]:
type(lst)

list

In [8]:
arr = np.array(lst)
arr

array([6, 9, 6, 5, 8, 9, 9, 5, 9, 5, 7, 8, 5, 9, 8])

In [9]:
type(arr)

numpy.ndarray

In [10]:
# Dimensions in numpy Arrays
# A deimension in arrays is one level of array depth (nested arrays)
# A nested array: are arrays that have arrays as their elements
arr_0 = np.array(45)
arr_0

array(45)

In [11]:
arr_0.ndim

0

In [12]:
# 1-D array:An array whose elements are 0-D array
arr_1 = np.array(lst)
arr_1

array([6, 9, 6, 5, 8, 9, 9, 5, 9, 5, 7, 8, 5, 9, 8])

In [13]:
arr_1.ndim

1

In [14]:
# 2-D array: an array whose elements are 1-D arrays

arr_2 = np.array([arr_1, arr_1 * 2])
arr_2

array([[ 6,  9,  6,  5,  8,  9,  9,  5,  9,  5,  7,  8,  5,  9,  8],
       [12, 18, 12, 10, 16, 18, 18, 10, 18, 10, 14, 16, 10, 18, 16]])

In [15]:
arr_2.ndim

2

In [16]:
arr_2.shape

(2, 15)

In [17]:
# 3-D array: An array that has 2-D arrays (matrices) as its elements
arr_3 = np.array([arr_2, arr_2 * 2])
arr_3

array([[[ 6,  9,  6,  5,  8,  9,  9,  5,  9,  5,  7,  8,  5,  9,  8],
        [12, 18, 12, 10, 16, 18, 18, 10, 18, 10, 14, 16, 10, 18, 16]],

       [[12, 18, 12, 10, 16, 18, 18, 10, 18, 10, 14, 16, 10, 18, 16],
        [24, 36, 24, 20, 32, 36, 36, 20, 36, 20, 28, 32, 20, 36, 32]]])

In [18]:
arr_3.ndim

3

In [19]:
len(arr_3)

2

In [20]:
arr_3.shape

(2, 2, 15)

In [22]:
arr_4 = np.array([1,2,3,4,5], ndmin=4)
arr_4

array([[[[1, 2, 3, 4, 5]]]])

In [23]:
arr_4.shape

(1, 1, 1, 5)

In [24]:
arr_1

array([6, 9, 6, 5, 8, 9, 9, 5, 9, 5, 7, 8, 5, 9, 8])

In [25]:
arr_1[0]

6

In [27]:
arr_1[14]

8

In [28]:
arr[-1]

8

In [29]:
arr_2.shape

(2, 15)

In [30]:
arr_2[0]

array([6, 9, 6, 5, 8, 9, 9, 5, 9, 5, 7, 8, 5, 9, 8])

In [31]:
arr_2[1]

array([12, 18, 12, 10, 16, 18, 18, 10, 18, 10, 14, 16, 10, 18, 16])

In [32]:
arr_2[1,-1]

16

In [33]:
arr_2[0,5]

9

In [34]:
arr_3

array([[[ 6,  9,  6,  5,  8,  9,  9,  5,  9,  5,  7,  8,  5,  9,  8],
        [12, 18, 12, 10, 16, 18, 18, 10, 18, 10, 14, 16, 10, 18, 16]],

       [[12, 18, 12, 10, 16, 18, 18, 10, 18, 10, 14, 16, 10, 18, 16],
        [24, 36, 24, 20, 32, 36, 36, 20, 36, 20, 28, 32, 20, 36, 32]]])

In [35]:
arr_3.shape

(2, 2, 15)

In [36]:
arr_3[0]

array([[ 6,  9,  6,  5,  8,  9,  9,  5,  9,  5,  7,  8,  5,  9,  8],
       [12, 18, 12, 10, 16, 18, 18, 10, 18, 10, 14, 16, 10, 18, 16]])

In [38]:
arr_3[1]

array([[12, 18, 12, 10, 16, 18, 18, 10, 18, 10, 14, 16, 10, 18, 16],
       [24, 36, 24, 20, 32, 36, 36, 20, 36, 20, 28, 32, 20, 36, 32]])

In [39]:
arr_3[1, 1]

array([24, 36, 24, 20, 32, 36, 36, 20, 36, 20, 28, 32, 20, 36, 32])

In [40]:
arr_3[1,1]

array([24, 36, 24, 20, 32, 36, 36, 20, 36, 20, 28, 32, 20, 36, 32])

In [41]:
arr_3[0,1,-1]

16

In [42]:
arr_3[0][1][-1]

16

In [45]:
# slicing numpy arrays: [start:end:step]
arr_1

array([6, 9, 6, 5, 8, 9, 9, 5, 9, 5, 7, 8, 5, 9, 8])

In [44]:
arr_1[0:10]

array([6, 9, 6, 5, 8, 9, 9, 5, 9, 5])

In [46]:
arr_1[-10:]

array([9, 9, 5, 9, 5, 7, 8, 5, 9, 8])

In [47]:
arr_1.shape

(15,)

In [48]:
arr_2

array([[ 6,  9,  6,  5,  8,  9,  9,  5,  9,  5,  7,  8,  5,  9,  8],
       [12, 18, 12, 10, 16, 18, 18, 10, 18, 10, 14, 16, 10, 18, 16]])

In [49]:
arr_2[:]

array([[ 6,  9,  6,  5,  8,  9,  9,  5,  9,  5,  7,  8,  5,  9,  8],
       [12, 18, 12, 10, 16, 18, 18, 10, 18, 10, 14, 16, 10, 18, 16]])

In [50]:
arr_2.shape

(2, 15)

In [51]:
arr_2[1, -5:]

array([14, 16, 10, 18, 16])